version: "3.8"
services:
  app:
    image: rahilshah/gif-collection:latest
    deploy:
      labels:
        traefik.http.routers.app.rule: Host(`app.localhost`)
        traefik.http.services.app.loadbalancer.server.port: 3000
    networks:
      - proxy
  mongo:
    image: mongo:4.4
    networks:
      - proxy
    deploy:
      replicas: 1
  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
    deploy:
      labels:
        traefik.http.routers.mongo-express.rule: Host(`mongo-express.localhost`)
        traefik.http.services.mongo-express.loadbalancer.server.port: 8081
    networks:
      - proxy
networks:
  proxy:
    external: true
  #monitoring:
  #  external: true

